### ISSUE TITLE
Активность кнопки "Задеплоить"

### ISSUE THREAD

**Issue by shyzik93** [TVP-Support/django_knowledge#40]
Потенциальная проблема:
Сейчас любой человек может нажимать кнопку деплоя сколь угодно раз подряд, что может привести к неопределённым последствиям.

Решение:
Кнопка активна, если на гитхабе существуют свежие коммиты (и их нет в ветке на сервере). Рядом указывать количество свежих коммитов.

В противном случае кнопка неактивна, выводится надпись о

**Comment by redboo** [comment]
@shyzik93 насколько актуальна данная проблема?

**Comment by shyzik93** [comment]
@redboo тема прикольная, например, позволила бы кому-то со стороны деплоить изменения на сервер, если я вдруг стану недоступен.

Задачу закрою, так как если что и случится, то сервер проработает недолго без оплаты. Так что, сообществу будет проще развернуть сервер на новом месте.
